In [1]:
import pandas as pd
df1 = pd.read_excel('Chinese_SME_ITOGOVYJ_VARIANT_2.xls', sheet_name=0)
df2 = pd.read_excel('Chinese_SME_ITOGOVYJ_VARIANT_2.xls', sheet_name=1)
df1.columns

Index(['Company Name', 'Exchange:Ticker', 'Primary Sector', 'Primary Industry',
       'Headquarters - Country/Region', 'Website', 'Business Description',
       'Country/Region of Incorporation', 'Geographic Region',
       'Operating Income [LTM] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2016] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2017] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2018] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2019] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2020] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2016] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2017] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2018] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2019] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2020] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2016] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2017] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2018] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2019] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2020] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2016] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2017] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2018] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2019] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2020] ($USDmm, 5/2/2020 rate)',
       'Return on Assets % [Latest Annual - 5]',
       'Return on Equity % [Latest Annual - 5]',
       'Gross Margin % [Latest Annual - 5]',
       'EBITDA Margin % [Latest Annual - 5]',
       'EBIT Margin % [Latest Annual - 5]', 'Board Members (Current Only)',
       'Number of Employees - Global (Latest)',
       '% of Directors that are External', '% of Directors that are Internal',
       'Year Founded',
       'Operating Income [Latest Annual - 5] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 9] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 8] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 7] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 6] ($USDmm, 5/2/2020 rate)',
       'Return on Assets % [Latest Annual - 4]',
       'Return on Assets % [Latest Annual - 3]',
       'Return on Assets % [Latest Annual - 2]',
       'Return on Assets % [Latest Annual - 1]',
       'Return on Assets % [Latest Annual]', 'Return on Assets % [FY 2016]',
       'Return on Assets % [FY 2017]', 'Return on Assets % [FY 2018]',
       'Return on Assets % [FY 2019]', 'Return on Assets % [FY 2020]',
       'Return on Equity % [FY 2016]', 'Return on Equity % [FY 2017]',
       'Return on Equity % [FY 2018]', 'Return on Equity % [FY 2019]',
       'Return on Equity % [FY 2020]', 'EBITDA Margin % [FY 2016]',
       'EBITDA Margin % [FY 2017]', 'EBITDA Margin % [FY 2018]',
       'EBITDA Margin % [FY 2019]', 'EBITDA Margin % [FY 2020]',
       'EBIT Margin % [FY 2016]', 'EBIT Margin % [FY 2017]',
       'EBIT Margin % [FY 2018]', 'EBIT Margin % [FY 2019]',
       'EBIT Margin % [FY 2020]', 'Salary  [FY 2016] ($USD, 5/2/2020 rate)',
       'Salary  [FY 2017] ($USD, 5/2/2020 rate)',
       'Salary  [FY 2018] ($USD, 5/2/2020 rate)',
       'Salary  [FY 2019] ($USD, 5/2/2020 rate)',
       'Total Annual Cash Compensation  [FY 2016] ($USD, 5/2/2020 rate)',
       'Total Annual Cash Compensation  [FY 2017] ($USD, 5/2/2020 rate)',
       'Total Annual Cash Compensation  [FY 2018] ($USD, 5/2/2020 rate)',
       'Total Annual Cash Compensation  [FY 2019] ($USD, 5/2/2020 rate)',
       'CEO - % Owned [Latest] (%)', 'CEO - % Owned [Latest Quarter-4] (%)',
       'CEO - % Owned [Latest Quarter-8] (%)',
       'CEO - % Owned [Latest Quarter-12] (%)',
       'CEO - % Owned [Latest Quarter-16] (%)',
       'CEO - Value Owned [Latest] ($USDmm, 5/2/2020 rate)',
       'CEO - Value Owned [Latest Quarter-4] ($USDmm, 5/2/2020 rate)',
       'CEO - Value Owned [Latest Quarter-8] ($USDmm, 5/2/2020 rate)',
       'CEO - Value Owned [Latest Quarter-12] ($USDmm, 5/2/2020 rate)',
       'CEO - Value Owned [Latest Quarter-16] ($USDmm, 5/2/2020 rate)',
       'Chairman - % Owned [Latest] (%)',
       'Chairman - % Owned [Latest Quarter-4] (%)',
       'Chairman - % Owned [Latest Quarter-8] (%)',
       'Chairman - % Owned [Latest Quarter-12] (%)',
       'Chairman - % Owned [Latest Quarter-16] (%)',
       'Chairman - Value Owned [Latest] ($USDmm, 5/2/2020 rate)',
       'Chairman - Value Owned [Latest Quarter-4] ($USDmm, 5/2/2020 rate)',
       'Chairman - Value Owned [Latest Quarter-8] ($USDmm, 5/2/2020 rate)',
       'Chairman - Value Owned [Latest Quarter-12] ($USDmm, 5/2/2020 rate)',
       'Chairman - Value Owned [Latest Quarter-16] ($USDmm, 5/2/2020 rate)'],
      dtype='object')

In [2]:
# Это название всех колонок, которые есть за пять лет, он взяты из свехру нужно руками редактировать немного 
value = [
       'Total Revenue [FY 2016] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2017] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2018] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2019] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [FY 2020] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2016] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2017] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2018] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2019] ($USDmm, 5/2/2020 rate)',
       'Total Assets [FY 2020] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2016] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2017] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2018] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2019] ($USDmm, 5/2/2020 rate)',
       'Total Assets [CY 2020] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2016] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2017] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2018] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2019] ($USDmm, 5/2/2020 rate)',
       'Total Revenue [CY 2020] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 9] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 8] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 7] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 6] ($USDmm, 5/2/2020 rate)',
       'Operating Income [Latest Annual - 5] ($USDmm, 5/2/2020 rate)','Return on Assets % [FY 2016]',
       'Return on Assets % [FY 2017]', 'Return on Assets % [FY 2018]',
       'Return on Assets % [FY 2019]', 'Return on Assets % [FY 2020]',
       'Return on Equity % [FY 2016]', 'Return on Equity % [FY 2017]',
       'Return on Equity % [FY 2018]', 'Return on Equity % [FY 2019]',
       'Return on Equity % [FY 2020]', 'EBITDA Margin % [FY 2016]',
       'EBITDA Margin % [FY 2017]', 'EBITDA Margin % [FY 2018]',
       'EBITDA Margin % [FY 2019]', 'EBITDA Margin % [FY 2020]',
       'EBIT Margin % [FY 2016]', 'EBIT Margin % [FY 2017]',
       'EBIT Margin % [FY 2018]', 'EBIT Margin % [FY 2019]',
       'EBIT Margin % [FY 2020]', 
       'CEO - % Owned [Latest] (%)', 'CEO - % Owned [Latest Quarter-4] (%)',
       'CEO - % Owned [Latest Quarter-8] (%)',
       'CEO - % Owned [Latest Quarter-12] (%)',
       'CEO - % Owned [Latest Quarter-16] (%)',
       'CEO - Value Owned [Latest] ($USDmm, 5/2/2020 rate)',
       'CEO - Value Owned [Latest Quarter-4] ($USDmm, 5/2/2020 rate)',
       'CEO - Value Owned [Latest Quarter-8] ($USDmm, 5/2/2020 rate)',
       'CEO - Value Owned [Latest Quarter-12] ($USDmm, 5/2/2020 rate)',
       'CEO - Value Owned [Latest Quarter-16] ($USDmm, 5/2/2020 rate)',
       'Chairman - % Owned [Latest] (%)',
       'Chairman - % Owned [Latest Quarter-4] (%)',
       'Chairman - % Owned [Latest Quarter-8] (%)',
       'Chairman - % Owned [Latest Quarter-12] (%)',
       'Chairman - % Owned [Latest Quarter-16] (%)',
       'Chairman - Value Owned [Latest] ($USDmm, 5/2/2020 rate)',
       'Chairman - Value Owned [Latest Quarter-4] ($USDmm, 5/2/2020 rate)',
       'Chairman - Value Owned [Latest Quarter-8] ($USDmm, 5/2/2020 rate)',
       'Chairman - Value Owned [Latest Quarter-12] ($USDmm, 5/2/2020 rate)',
       'Chairman - Value Owned [Latest Quarter-16] ($USDmm, 5/2/2020 rate)']

In [3]:
#Имена новых переменных уже преобрахованных данных
cols = ['Company Name',
        'Years',
       'Total Revenue',
       'Total Assets [FY]',
       'Total Assets [CY]',
       'Total Revenue [CY]',
       'Operating Income',
       'Return on Assets %',
       'Return on Equity %',
       'EBITDA Margin %',
       'EBIT Margin %',
       'CEO - % Owned',
       'CEO - Value Owned',
       'Chairman - % Owned',
       'Chairman - Value Owned'
]

In [4]:
# Создаю пустой массив, чтобы его заполнить числами
import numpy as np
arr = np.zeros((df1.shape[0] * 5, len(cols)))

In [5]:
# Заменяю все прочерки и NM на 999999999, т.к. массив может содержать только числа
df1 = df1.replace('-', 999999999)
df1 = df1.replace('NM', 999999999)
# Создаю пустой массив, чтобы его заполнить числами
import numpy as np
arr = np.zeros((df1.shape[0] * 5, len(cols)))

# Сам цикл
for i in range(2, len(cols)):
    counter = 0
    for j in df1['Company Name']:
        year = 2016
        for n in range(5*(i-2), 5*(i-1)):
            arr[counter][i] =  df1[value[n]][df1['Company Name'] == j].values[0]

            arr[counter][1] = year
            counter += 1
            year += 1

In [6]:
# Записываю все значения в таблицу
tot = pd.DataFrame(arr,columns=cols)
# Преобразую года из числового формата в во временной
tot.Years = pd.to_datetime(tot.Years, format='%Y')
# Создаю таблицу для названия компаний
names = []
for i in df1['Company Name']:
    for j in range(5):
        names.append(i)
tot['Company Name'] = names

In [7]:
# Доделывал отдельно с данными, где есть строки и цифры вместе
x = ['Salary  [FY 2016] ($USD, 5/2/2020 rate)',
       'Salary  [FY 2017] ($USD, 5/2/2020 rate)',
       'Salary  [FY 2018] ($USD, 5/2/2020 rate)',
       'Salary  [FY 2019] ($USD, 5/2/2020 rate)',
       'Total Annual Cash Compensation  [FY 2016] ($USD, 5/2/2020 rate)',
       'Total Annual Cash Compensation  [FY 2017] ($USD, 5/2/2020 rate)',
       'Total Annual Cash Compensation  [FY 2018] ($USD, 5/2/2020 rate)',
       'Total Annual Cash Compensation  [FY 2019] ($USD, 5/2/2020 rate)'
]

In [8]:
import re
arr = np.zeros((df1.shape[0]*5, 2))
for i in range(2):
    counter = 0
    for j in df1['Company Name']:
        con = 1
        for n in range(4*(i), 4*(i+1)):
            s = df1[x[n]][df1['Company Name'] == j].values[0]
            s = re.sub('[A-z () ;’-]', ' ', s)
            if '’' in s: print(s)
            s = re.sub(',', '',s).split()
            s = [int(word) for word in s if word.isdigit()]
            np.mean(s)
            arr[counter][i] =  np.mean(s)
            counter += 1 
            con += 1
        arr[counter][i] =  999999999
        counter += 1
    
tot['Salary'] = arr[:, 0]
tot['Total annual Cash'] = arr[:, 1]
# Добавил число сотрудников
employees = []
for i in df1['Number of Employees - Global (Latest)']:
    for j in range(5):
        employees.append(i)
tot['Number of Employees'] = employees
# Вернул все пропуски к прочеркам
tot = tot.replace(999999999, '-')
tot.head()

,Company Name,Years,Total Revenue,Total Assets [FY],Total Assets [CY],Total Revenue [CY],Operating Income,Return on Assets %,Return on Equity %,EBITDA Margin %,EBIT Margin %,CEO - % Owned,CEO - Value Owned,Chairman - % Owned,Chairman - Value Owned,Salary,Total annual Cash,Number of Employees
0,Industrial and Commercial Bank of China Limite...,2016-01-01,78592.3,3.4183e+06,3.4183e+06,78592.3,30564.9,1.2,14.8,-,-,-,-,-,-,36788.1,61952.6,445106
1,Industrial and Commercial Bank of China Limite...,2017-01-01,85061.9,3.69442e+06,3.69442e+06,85061.9,38420.2,1.15,13.9,-,-,-,-,-,-,81175.8,71761.1,445106
2,Industrial and Commercial Bank of China Limite...,2018-01-01,87135.8,3.92278e+06,3.92278e+06,87135.8,43592.6,1.11,13.3,-,-,-,-,-,-,76482,70914.2,445106
3,Industrial and Commercial Bank of China Limite...,2019-01-01,96243,4.26407e+06,4.26407e+06,96243,47932.1,1.08,12.4,-,-,-,-,-,-,70450,68926,445106
4,Industrial and Commercial Bank of China Limite...,2020-01-01,-,-,-,-,51236.2,-,-,-,-,-,-,-,-,-,-,445106

In [10]:
tot.to_excel('vot1.xls')